name: 'Wait for commit statuses'
description: 'Wait for commit statuses to be either successful or failed'
branding:
  icon: 'clock'
  color: 'orange'
inputs:
  ignoreActions:
    description: 'CSV of action names to ignore'
    required: true
  checkInterval:
    description: 'Time between checks (in seconds)'
    required: false
    default: 10
outputs:
  status:
    description: 'Success or failure'
runs:
  using: 'docker'
  image: 'Dockerfile'