name: 'Wait for commit statuses'
description: 'Wait for commit statuses to be either successful or failed'
branding:
  icon: 'clock'
  color: 'orange'
inputs:
  ignoreActions:
    description: 'CSV of action names to ignore. Note that these names are the human readable names use as status on commits, and show up as status checks on PRs.'
    required: true
  checkInterval:
    description: 'Time between checks (in seconds)'
    required: false
    default: 10
  waitForCheck:
    description: 'Whether to wait for a check if none are present'
    required: false
    default: ""
  commitSha:
    description: 'Overwrite the default detected GITHUB_SHA'
    required: false
    default: ""
outputs:
  status:
    description: 'Success or failure'
runs:
  using: 'docker'
  image: 'Dockerfile'
