# syntax=docker/dockerfile:experimental
FROM ghcr.io/wyrihaximusnet/php:7.4-nts-alpine-dev-root AS install-dependencies
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN mkdir /workdir
WORKDIR /workdir
COPY ./src /workdir/src
COPY ./composer.* ./wait.php /workdir/
RUN composer install --ansi --no-progress --no-interaction --prefer-dist --no-dev

## Compile runtime image
FROM ghcr.io/wyrihaximusnet/php:7.4-nts-alpine-root AS runtime
RUN mkdir /workdir
WORKDIR /workdir
COPY --from=install-dependencies /workdir/ /workdir/
RUN ls -lasth ./
ENTRYPOINT ["php", "/workdir/wait.php"]
